platform :ios, '9.0'
use_frameworks!
inhibit_all_warnings!
use_modular_headers!

target 'RNMapboxNavigation' do
 pod 'Mapbox-iOS-SDK'
 pod 'MapboxNavigation'
 pod 'MapboxGeocoder.swift'
 pod 'MapboxDirections.swift'
end